{
 "title": "Электрика",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "imei",
    "label": "IMEI",
    "query": {
     "query": "label_values(galileosky_mercury_u1,imei)"
    }
   },
   {
    "name": "mercury_id",
    "label": "ID счетчика",
    "query": {
     "query": "label_values(galileosky_mercury_u1,addr)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Общие данные", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Статус электросчетчика",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_state{addr=\"$mercury_id\", imei=\"$imei\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Частота сети",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_f{addr=\"$mercury_id\", imei=\"$imei\"} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза A, (V)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_u1{addr=\"$mercury_id\", imei=\"$imei\"} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза B, (V)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_u2{addr=\"$mercury_id\", imei=\"$imei\"} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза C, (V)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_u3{addr=\"$mercury_id\", imei=\"$imei\"} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза A, (А)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_i1{addr=\"$mercury_id\", imei=\"$imei\"} / 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза B, (А)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_i2{addr=\"$mercury_id\", imei=\"$imei\"} / 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза C, (А)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_i3{addr=\"$mercury_id\", imei=\"$imei\"} / 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Текущий угол между гармониками фаз A-B, градусы",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_a12{addr=\"$mercury_id\", imei=\"$imei\"} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Текущий угол между гармониками фаз B-C, градусы",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_a23{addr=\"$mercury_id\", imei=\"$imei\"} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Текущий угол между гармониками фаз A-C, градусы",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_a13{addr=\"$mercury_id\", imei=\"$imei\"} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Суммарное значение потребляемой активной энергии, кВт/ч",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_ps{addr=\"$mercury_id\", imei=\"$imei\"} / 100000 * 6 * 300",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза A: Значение потребляемой активной энергии, кВт/ч",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_p1{addr=\"$mercury_id\", imei=\"$imei\"} / 100000 * 6 * 300",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза B: Значение потребляемой активной энергии, кВт/ч",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_p2{addr=\"$mercury_id\", imei=\"$imei\"} / 100000 * 6 * 300",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза С: Значение потребляемой активной энергии, кВт/ч",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_p3{addr=\"$mercury_id\", imei=\"$imei\"} / 100000 * 6 * 300",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cуммарный коэффициент мощности",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_kss{addr=\"$mercury_id\", imei=\"$imei\"} / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза A: Коэффициент мощности",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_ks1{addr=\"$mercury_id\", imei=\"$imei\"} / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза B: Коэффициент мощности",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_ks2{addr=\"$mercury_id\", imei=\"$imei\"} / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза C: Коэффициент мощности",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_ks3{addr=\"$mercury_id\", imei=\"$imei\"} / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза A: Коэффициент искажения синусоидальности фазных напряжений",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_kg1{addr=\"$mercury_id\", imei=\"$imei\"} / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза B: Коэффициент искажения синусоидальности фазных напряжений",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_kg2{addr=\"$mercury_id\", imei=\"$imei\"} / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза C: Коэффициент искажения синусоидальности фазных напряжений",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_kg3{addr=\"$mercury_id\", imei=\"$imei\"} / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Активная прямая энергия, учтенная электросчетчиком с момента сброса, кВт*ч",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_pa_plus{addr=\"$mercury_id\", imei=\"$imei\"} / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Графики",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Текущее потребление тока, А",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "galileosky_mercury_i1{addr=\"$mercury_id\", imei=\"$imei\"} / 10",
       "legendFormat": "Фаза A"
      },
      {
       "expr": "galileosky_mercury_i2{addr=\"$mercury_id\", imei=\"$imei\"} / 10",
       "legendFormat": "Фаза B"
      },
      {
       "expr": "galileosky_mercury_i3{addr=\"$mercury_id\", imei=\"$imei\"} / 10",
       "legendFormat": "Фаза C"
      }
     ]
    },
    {
     "title": "Суммарное значение потребляемой активной энергии, кВт/ч",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "galileosky_mercury_ps{addr=\"$mercury_id\", imei=\"$imei\"} / 100000 * 6 * 300",
       "legendFormat": "galileosky_mercury_ps"
      }
     ]
    }
   ]
  }
 ]
}