{
 "title": "Mercury 230 Dashboard (Loki)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "imei",
    "label": "IMEI",
    "query": "label_values({job=\"mercury_parser\"}, imei)"
   },
   {
    "name": "mercury_id",
    "label": "ID счетчика",
    "query": "label_values({job=\"mercury_parser\"}, mercury_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Ticks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg by (mercury_id, imei) (last_over_time({job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} | json | unwrap enter1 | __error__=`` [5m]))",
     "legendFormat": "Фаза A"
    }
   ]
  },
  { "title": "Общие данные", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Статус электросчетчика",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "max by (mercury_id, imei) (last_over_time({job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} | json | unwrap galileosky_mercury_state | __error__=\"\" [5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Частота сети",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mercury_id, imei) (last_over_time({job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} | json | unwrap galileosky_mercury_f | __error__=\"\" [5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза A, (А)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "min by (mercury_id, imei) (last_over_time({job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} | json | unwrap galileosky_mercury_i1 | __error__=\"\" [1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза A, (V)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "max by (mercury_id, imei) (\n  last_over_time(\n    {job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} \n    | json \n    | unwrap galileosky_mercury_u1 \n    | __error__=\"\" \n    [$__range]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Текущий угол между гармониками фаз A-B, градусы",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mercury_id, imei) (last_over_time({job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} | json | unwrap galileosky_mercury_a12 | __error__=\"\" [5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза B, (А)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "min by (mercury_id, imei) (last_over_time({job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} | json | unwrap galileosky_mercury_i2 | __error__=\"\" [1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза B, (V)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "max by (mercury_id, imei) (\n  last_over_time(\n    {job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} \n    | json \n    | unwrap galileosky_mercury_u2 \n    | __error__=\"\" \n    [$__range]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cуммарный коэффициент мощности",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mercury_id, imei) (last_over_time({job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} | json | unwrap galileosky_mercury_kss | __error__=\"\" [5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза C, (А)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "min by (mercury_id, imei) (last_over_time({job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} | json | unwrap galileosky_mercury_i3 | __error__=\"\" [1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза C, (V)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "max by (mercury_id, imei) (\n  last_over_time(\n    {job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} \n    | json \n    | unwrap galileosky_mercury_u3\n    | __error__=\"\" \n    [$__range]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Суммарное значение потребляемой активной энергии, кВт/ч",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "min by (mercury_id, imei) (last_over_time({job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} | json | unwrap galileosky_mercury_ps | __error__=\"\" [1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Текущий угол между гармониками фаз B-C, градусы",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mercury_id, imei) (last_over_time({job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} | json | unwrap galileosky_mercury_a23 | __error__=\"\" [5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Текущий угол между гармониками фаз A-C, градусы",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mercury_id, imei) (last_over_time({job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} | json | unwrap galileosky_mercury_a13 | __error__=\"\" [5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза A: Коэффициент мощности",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "max by (mercury_id, imei) (last_over_time({job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} | json | unwrap galileosky_mercury_ks1 | __error__=\"\" [5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза B: Коэффициент мощности",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mercury_id, imei) (last_over_time({job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} | json | unwrap galileosky_mercury_ks2 | __error__=\"\" [5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза C: Коэффициент мощности",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "max by (mercury_id, imei) (last_over_time({job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} | json | unwrap galileosky_mercury_ks3 | __error__=\"\" [5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза A: Коэффициент искажения синусоидальности фазных напряжений",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mercury_id, imei) (last_over_time({job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} | json | unwrap galileosky_mercury_kg1 | __error__=\"\" [5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза B: Коэффициент искажения синусоидальности фазных напряжений",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mercury_id, imei) (last_over_time({job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} | json | unwrap galileosky_mercury_kg2 | __error__=\"\" [5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Фаза C: Коэффициент искажения синусоидальности фазных напряжений",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mercury_id, imei) (last_over_time({job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} | json | unwrap galileosky_mercury_kg3 | __error__=\"\" [5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Активная прямая энергия, учтенная электросчетчиком с момента сброса, кВт*ч",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mercury_id, imei) (last_over_time({job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} | json | unwrap galileosky_mercury_pa_plus | __error__=\"\" [5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Графики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Текущее потребление тока, А",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "direction": "backward",
     "expr": "max by (mercury_id, imei) (avg_over_time({job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} | json | unwrap galileosky_mercury_i1 | __error__=\"\" [$__interval])) * 100",
     "legendFormat": "Фаза A"
    },
    {
     "direction": "backward",
     "expr": "max by (mercury_id, imei) (avg_over_time({job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} | json | unwrap galileosky_mercury_i2 | __error__=\"\" [$__interval])) * 100",
     "legendFormat": "Фаза B"
    },
    {
     "direction": "backward",
     "expr": "max by (mercury_id, imei) (avg_over_time({job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} | json | unwrap galileosky_mercury_i3 | __error__=\"\" [$__interval])) * 100",
     "legendFormat": "Фаза C"
    }
   ]
  },
  {
   "title": "Суммарное значение потребляемой активной энергии, кВт/ч",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "direction": "backward",
     "expr": "max by (mercury_id, imei) (avg_over_time({job=\"mercury_parser\", mercury_id=~\"$mercury_id\", imei=~\"$imei\"} | json | unwrap galileosky_mercury_ps | __error__=\"\" [$__interval]))",
     "legendFormat": "galileosky_mercury_ps"
    }
   ]
  }
 ]
}