{
 "title": "Дашборд c 12",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "imei",
    "label": "IMEI",
    "query": "label_values({job=\"mercury_parser\"}, imei)"
   },
   {
    "name": "mercury_id",
    "label": "ID счетчика",
    "query": "Контейнер 1 : 99, Контейнер 2 : 73, Контейнер 3 : 22, Контейнер 4 : 89, Контейнер 5 : 77, Контейнер 6 : 95,  Контейнер 7 : 94, Контейнер 8 : 92, Контейнер 9 : 27,  Контейнер 10 : 68, Контейнер 11 : 41, Контейнер 12 : 900, Контейнер 12.1 : 61, Контейнер 12.2 : 6, Контейнер 12.3 : 128  ,Контейнер 13 : 2"
   }
  ]
 },
 "panels": [
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Сила тока фаза A, (А)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_current{phase=\"1\", mercury_id=\"$mercury_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Сила тока фаза В, (А)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_current{phase=\"2\", mercury_id=\"$mercury_id\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Сила тока фаза С, (А)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_current{phase=\"3\", mercury_id=\"$mercury_id\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потребляемой активной энергии, кВт/ч",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_active_power{phase=\"sum\", mercury_id=\"$mercury_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Показания счётчика, кВт*ч",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_active_energy_fwd{ mercury_id=\"$mercury_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hz",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_frequency{mercury_id=\"$mercury_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Сила тока, А;B;C",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "avg_over_time(galileosky_mercury_current{mercury_id=\"$mercury_id\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потребление, кВт/ч",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "max_over_time(galileosky_mercury_active_power{phase=\"sum\", mercury_id=\"$mercury_id\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Напряжение фаза A, (V)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(galileosky_mercury_voltage{phase=\"1\", mercury_id=\"$mercury_id\"} [1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Напряжение фаза B, (V)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_voltage{phase=\"2\", mercury_id=\"$mercury_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Напряжение фаза C, (V)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_voltage{phase=\"3\", mercury_id=\"$mercury_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Температура Трансформатора",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 9, "y": 18 },
   "targets": [
    {
     "expr": "avg_over_time(galileosky_temperature{sensor_id=\"3\", mercury_id=\"$mercury_id\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Температура Силового ввода:A;B;C",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "avg_over_time(galileosky_temperature{sensor_id=~\"1|0|2\", mercury_id=\"$mercury_id\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cos φ фаза A",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_power_factor{phase=\"1\", mercury_id=\"$mercury_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cos φ фаза B",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_power_factor{phase=\"2\",mercury_id=\"$mercury_id\"}"
    }
   ]
  },
  {
   "title": "cos φ фаза C",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_power_factor{phase=\"3\", mercury_id=\"$mercury_id\"}"
    }
   ]
  },
  {
   "title": "Угол м/у гармониками фаз A-B",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_angle{phase_pair=\"1-2\", mercury_id=~\"$mercury_id\"}"
    }
   ]
  },
  {
   "title": "Угол м/у гармониками фаз A-C",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_angle{phase_pair=\"1-3\", mercury_id=~\"$mercury_id\"}"
    }
   ]
  },
  {
   "title": "Угол м/у гармониками фаз B-C",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_angle{phase_pair=\"2-3\", mercury_id=~\"$mercury_id\"}"
    }
   ]
  },
  {
   "title": "sin фаза A",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_distortion{phase=\"1\", mercury_id=~\"$mercury_id\"}"
    }
   ]
  },
  {
   "title": "sin фаза B",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_distortion{phase=\"2\", mercury_id=~\"$mercury_id\"}"
    }
   ]
  },
  {
   "title": "sin фаза C",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "galileosky_mercury_distortion{phase=\"3\", mercury_id=~\"$mercury_id\"}"
    }
   ]
  }
 ]
}